title: Sinimandria
email: your-email@example.com
description: >-
  Üks hea brunchikoht
baseurl: ""
url: "https://sinimandira.ee"
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: null
plugins:
  - jekyll-feed

sass:
  style: compressed
