title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here...
baseurl: "/sinimandria"
url: "https://m-tu.github.io"
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: null
plugins:
  - jekyll-feed

sass:
  style: compressed
