title: Sinimandria
email: your-email@example.com
description: >-
  Üks hea brunchikoht
baseurl: "/sinimandria"
url: "https://m-tu.github.io"
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: null
plugins:
  - jekyll-feed

sass:
  style: compressed
